version: '3.1'

services:

  docker-mysql-category:
    restart: always
    container_name: docker-mysql-category
    image: mysql
    environment:
      MYSQL_DATABASE: category
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6035:3306"

